### ISSUE TITLE
Project Submission

### ISSUE THREAD

**Issue by valentinboyanov** [onesdata/catalog-consistency-checks#10]
![Hack Friday 2020 General Intro - Google Slides 11-22-2020 11-00-06 AM](https://user-images.githubusercontent.com/2522812/99900774-e2c00280-2cb1-11eb-912e-cf3c45f410bf.png)

In order to submit our proposal we need:
- [x] navigation within the shopify admin minimally usable
- [x] description of the app for the jury
- [x] prepare a demo with screenshots and links to show the value proposition
- [x] submit the project before 3 PM: [form](https://forms.gle/vsaUmEECQTvgHApK8)

**Comment by j-plou** [comment]
Project presentation in #13

**Comment by j-plou** [comment]
Project submitted :tada:
